// ═══════════════════════════════════════════════════════════════
// metal_bridge.mm — S-MoE Engine · Objective-C++ Metal Bridge
// ═══════════════════════════════════════════════════════════════
// Architecture:
//   JIT compile the MSL source via newLibraryWithSource: at init and
//   build one PSO per kernel (fused FFN passes, bf16 matvecs, decode
//   attention). Every CPU pointer the GPU touches is registered once
//   via newBufferWithBytesNoCopy — zero-copy through UMA.
//
// Design invariants (CLAUDE.md):
//   ① No malloc/new in the hot dispatch path — all resources
//     pre-allocated in smoe_metal_init().
//   ② UMA buffers in MTLResourceStorageModeShared: pread() from
//     the I/O streamer and the GPU shader access the same pages.
//   ③ Synchronisation via std::atomic + MTLSharedEvent, never OS
//     mutexes.
// ═══════════════════════════════════════════════════════════════

#import  <Foundation/Foundation.h>
#import  <Metal/Metal.h>

#include "metal_bridge.h"
#include "../common.hpp"

#include <atomic>
#include <cstdio>
#include <cstring>
#include <vector>
#include <cstdlib>
#include <cstdarg>
#include <thread>

static void info_printf(const char* format, ...) {
    static const bool enabled = [] {
        const char* sm_dbg = std::getenv("SMOE_DEBUG");
        return sm_dbg && (std::strcmp(sm_dbg, "1") == 0 ||
                          std::strcmp(sm_dbg, "true") == 0);
    }();
    if (!enabled) return;
    va_list args;
    va_start(args, format);
    std::vfprintf(stderr, format, args);
    va_end(args);
}

// ── Embedded MSL source ───────────────────────────────────────
// Generated by make from src/compute/kernels.metal (the single
// source of truth for the GPU kernels) and JIT-compiled at boot so
// the binary stays self-contained.
#include "kernels_msl.h"

// ═══════════════════════════════════════════════════════════════
// SmoeMetalCtx — internal implementation struct
// ═══════════════════════════════════════════════════════════════
struct Dims {
    uint32_t rows;
    uint32_t cols;
};

struct SmoeMetalCtx {
    id<MTLDevice>               device       = nil;
    id<MTLCommandQueue>         queue        = nil;
    id<MTLLibrary>              library      = nil;
    id<MTLComputePipelineState> gate_up_pso  = nil;
    id<MTLComputePipelineState> down_pso     = nil;
    id<MTLComputePipelineState> scout_matvec_bf16_pso = nil;
    id<MTLComputePipelineState> scout_matvec_bf16_sg_pso = nil;
    id<MTLComputePipelineState> attn_prep_pso   = nil;
    id<MTLComputePipelineState> attn_decode_pso = nil;
    id<MTLComputePipelineState> gate_up_batch_pso = nil;
    id<MTLComputePipelineState> down_batch_pso    = nil;

    // Token-batch fused FFN staging (layer-major prefill):
    //   batch_in  [SMOE_MAX_FFN_BATCH × gate_cols]
    //   batch_hid [SMOE_MAX_FFN_BATCH × gate_rows]
    //   batch_out [SMOE_MAX_FFN_BATCH × down_rows]
    // Dim cap: SMOE_MAX_FFN_BATCH_DIM floats per row.
    id<MTLBuffer>               batch_in_buf     = nil;
    id<MTLBuffer>               batch_hidden_buf = nil;
    id<MTLBuffer>               batch_out_buf    = nil;

    // Pre-allocated scratch buffer for the hidden activation vector.
    // Size = max_rows * sizeof(float). Allocated in smoe_metal_init.
    id<MTLBuffer>               hidden_buf   = nil;
    id<MTLBuffer>               output_buf   = nil;
    id<MTLBuffer>               input_buf    = nil;

    size_t                      slot_bytes   = 0;
    uint32_t                    max_rows     = 0;    // = slot_bytes / sizeof(float)
    size_t                      max_tg_mem   = 0;    // device threadgroup memory limit

    // Telemetry
    std::atomic<uint64_t>       dispatch_count { 0 };

    // Shared event for async GPU/CPU synchronisation
    id<MTLSharedEvent>          shared_event = nil;
    uint64_t                    signaled_value = 0;

    struct RegisteredBuffer {
        const void* ptr;
        size_t length;
        id<MTLBuffer> buffer;
    };
    std::vector<RegisteredBuffer> registered_buffers;
};

static id<MTLBuffer> get_registered_buffer(SmoeMetalCtx* ctx, const void* ptr, size_t sz, NSUInteger& out_offset) {
    uintptr_t p = reinterpret_cast<uintptr_t>(ptr);
    for (const auto& reg : ctx->registered_buffers) {
        uintptr_t base = reinterpret_cast<uintptr_t>(reg.ptr);
        if (p >= base && (p + sz) <= (base + reg.length)) {
            out_offset = p - base;
            return reg.buffer;
        }
    }
    
    uintptr_t aligned_p = p & ~(smoe::PAGE_SIZE - 1);
    out_offset = p - aligned_p;
    size_t aligned_sz = ((p + sz + (smoe::PAGE_SIZE - 1)) & ~(smoe::PAGE_SIZE - 1)) - aligned_p;
    id<MTLBuffer> buf = [ctx->device newBufferWithBytesNoCopy:reinterpret_cast<void*>(aligned_p)
                                          length:aligned_sz
                                         options:MTLResourceStorageModeShared
                                     deallocator:nil];
    if (buf) {
        ctx->registered_buffers.push_back({reinterpret_cast<const void*>(aligned_p), aligned_sz, buf});
    }
    return buf;
}

// ── Internal helpers ──────────────────────────────────────────

// Build a compute PSO from a function name in the already-compiled library.
static id<MTLComputePipelineState> make_pso(
    id<MTLDevice>  device,
    id<MTLLibrary> lib,
    const char*    fn_name,
    NSError**      err)
{
    NSString* name = [NSString stringWithUTF8String:fn_name];
    id<MTLFunction> fn = [lib newFunctionWithName:name];
    if (!fn) {
        std::fprintf(stderr,
            "[smoe_metal] ERROR: function '%s' not found in library.\n", fn_name);
        return nil;
    }
    return [device newComputePipelineStateWithFunction:fn error:err];
}

// ── Public API ────────────────────────────────────────────────

SmoeMetalCtx* smoe_metal_init(size_t slot_bytes) {
    // ── Step 1: acquire the default Metal device ──────────────
    id<MTLDevice> dev = MTLCreateSystemDefaultDevice();
    if (!dev) {
        std::fprintf(stderr, "[smoe_metal] ERROR: No Metal device found.\n");
        return nullptr;
    }

    // ── Step 2: JIT-compile the embedded MSL source ───────────
    // This takes ~200–500 ms on first run; the compiled PSO is
    // cached by the Metal compiler for subsequent launches.
    info_printf("[smoe_metal] Compiling SMOE-Q2 kernels (JIT)...\n");

    NSError*  err    = nil;
    NSString* source = [NSString stringWithUTF8String:kMetalSource];

    MTLCompileOptions* opts = [[MTLCompileOptions alloc] init];
    opts.languageVersion = MTLLanguageVersion3_1;
    opts.fastMathEnabled = YES;  // safe for our affine dequant formula

    id<MTLLibrary> lib = [dev newLibraryWithSource:source
                                           options:opts
                                             error:&err];
    if (!lib) {
        std::fprintf(stderr,
            "[smoe_metal] ERROR: MSL compilation failed:\n%s\n",
            [[err localizedDescription] UTF8String]);
        return nullptr;
    }
    info_printf("[smoe_metal] Kernel compilation OK.\n");

    // ── Step 3: build PSOs ────────────────────────────────────
    id<MTLComputePipelineState> gate_up_pso = make_pso(dev, lib, "smoe_gate_up", &err);
    if (!gate_up_pso) {
        std::fprintf(stderr,
            "[smoe_metal] ERROR: PSO 'smoe_gate_up' build failed:\n%s\n",
            [[err localizedDescription] UTF8String]);
        return nullptr;
    }

    id<MTLComputePipelineState> down_pso = make_pso(dev, lib, "smoe_down", &err);
    if (!down_pso) {
        std::fprintf(stderr,
            "[smoe_metal] ERROR: PSO 'smoe_down' build failed:\n%s\n",
            [[err localizedDescription] UTF8String]);
        return nullptr;
    }

    // ── Step 4: allocate scratch buffers ──────────────────────
    // MTLResourceStorageModeShared: CPU writes and GPU shaders
    // access the same physical pages — zero-copy guaranteed.
    MTLResourceOptions uma = MTLResourceStorageModeShared;

    // Sized for the worst-case intermediate dim x 8 concurrent experts.
    uint32_t max_rows    = static_cast<uint32_t>(
        std::min(slot_bytes / sizeof(float), size_t(32768)));
    id<MTLBuffer> hidden = [dev newBufferWithLength:16 * max_rows * sizeof(float)
                                            options:MTLResourceStorageModeShared];
    id<MTLBuffer> output_b = [dev newBufferWithLength:16 * max_rows * sizeof(float)
                                            options:uma];
    id<MTLBuffer> input_b = [dev newBufferWithLength:8192 * sizeof(float)
                                            options:uma];
    if (!hidden || !output_b || !input_b) {
        std::fprintf(stderr,
            "[smoe_metal] ERROR: Failed to allocate hidden/output/input scratch buffers.\n");
        return nullptr;
    }

    // ── Step 5: create command queue & shared event ──────────
    id<MTLCommandQueue> queue = [dev newCommandQueue];
    if (!queue) {
        std::fprintf(stderr, "[smoe_metal] ERROR: Failed to create command queue.\n");
        return nullptr;
    }
    id<MTLSharedEvent> shared_ev = [dev newSharedEvent];

    // ── Step 6: assemble context ──────────────────────────────
    SmoeMetalCtx* ctx = new SmoeMetalCtx();
    ctx->device      = dev;
    ctx->queue       = queue;
    ctx->library     = lib;
    ctx->gate_up_pso = gate_up_pso;
    ctx->down_pso    = down_pso;


    id<MTLComputePipelineState> scout_matvec_bf16_pso = make_pso(dev, lib, "scout_matvec_bf16", &err);
    if (!scout_matvec_bf16_pso) {
        std::fprintf(stderr,
            "[smoe_metal] ERROR: PSO 'scout_matvec_bf16' build failed:\n%s\n",
            [[err localizedDescription] UTF8String]);
        return nullptr;
    }
    ctx->scout_matvec_bf16_pso = scout_matvec_bf16_pso;

    // Coalesced twin — non-fatal if unavailable: every dispatch site
    // falls back to the thread-per-row PSO when this one is nil.
    ctx->scout_matvec_bf16_sg_pso = make_pso(dev, lib, "scout_matvec_bf16_sg", &err);
    if (!ctx->scout_matvec_bf16_sg_pso) {
        std::fprintf(stderr, "[smoe_metal] WARN: PSO 'scout_matvec_bf16_sg' unavailable — thread-per-row bf16 path only.\n");
    }
    ctx->max_tg_mem = [dev maxThreadgroupMemoryLength];

    ctx->attn_prep_pso   = make_pso(dev, lib, "attn_prep", &err);
    ctx->attn_decode_pso = make_pso(dev, lib, "attn_decode", &err);
    if (!ctx->attn_prep_pso || !ctx->attn_decode_pso) {
        std::fprintf(stderr,
            "[smoe_metal] ERROR: attention PSO build failed:\n%s\n",
            err ? [[err localizedDescription] UTF8String] : "(no detail)");
        return nullptr;
    }

    // Token-batch FFN: non-fatal if unavailable — callers fall back to
    // the per-token fused FFN path when these PSOs/buffers are nil.
    ctx->gate_up_batch_pso = make_pso(dev, lib, "smoe_gate_up_batch", &err);
    ctx->down_batch_pso    = make_pso(dev, lib, "smoe_down_batch", &err);
    if (ctx->gate_up_batch_pso && ctx->down_batch_pso) {
        // Row cap is SMOE_MAX_FFN_BATCH_DIM floats; ~4 MB per plane at
        // 64 × 16384 × 4 B. Shared-mode: CPU memcpy in, GPU writes out.
        size_t plane = size_t(SMOE_MAX_FFN_BATCH) * SMOE_MAX_FFN_BATCH_DIM * sizeof(float);
        ctx->batch_in_buf     = [dev newBufferWithLength:plane options:uma];
        ctx->batch_hidden_buf = [dev newBufferWithLength:plane options:uma];
        ctx->batch_out_buf    = [dev newBufferWithLength:plane options:uma];
        if (!ctx->batch_in_buf || !ctx->batch_hidden_buf || !ctx->batch_out_buf) {
            std::fprintf(stderr, "[smoe_metal] WARN: batch FFN staging alloc failed — per-token path only.\n");
            ctx->gate_up_batch_pso = nil;
            ctx->down_batch_pso    = nil;
        }
    } else {
        std::fprintf(stderr, "[smoe_metal] WARN: batch FFN PSOs unavailable — per-token path only.\n");
    }

    ctx->hidden_buf  = hidden;
    ctx->output_buf  = output_b;
    ctx->input_buf   = input_b;
    ctx->slot_bytes  = slot_bytes;
    ctx->max_rows    = max_rows;
    ctx->shared_event = shared_ev;
    ctx->signaled_value = 0;
    ctx->dispatch_count.store(0, std::memory_order_relaxed);

    info_printf(
        "[smoe_metal] Init OK — slot=%.1f MB, hidden_scratch=%u floats.\n",
        double(slot_bytes) / (1024.0 * 1024.0), max_rows);

    return ctx;
}

void smoe_metal_destroy(SmoeMetalCtx* ctx) {
    if (!ctx) return;
    // ARC handles all id<MTL*> release; we only need to free the struct.
    delete ctx;
}

void* smoe_metal_fused_ffn(SmoeMetalCtx*   ctx,
                           const uint8_t*  packed_gate,
                           const uint16_t* scales_gate,
                           const uint8_t*  packed_up,
                           const uint16_t* scales_up,
                           const uint8_t*  packed_down,
                           const uint16_t* scales_down,
                           const float*    input_vec,
                           float*          hidden_vec,
                           float*          output_vec,
                           uint32_t        gate_rows,
                           uint32_t        gate_cols,
                           uint32_t        down_rows,
                           uint32_t        down_cols,
                           uint32_t        group_size,
                           uint32_t        bits,
                           uint32_t        expert_index)
{
    if (!ctx) return nullptr;

    // ── Build FusedFFNParams ──────────────────────────────────
    // Stack allocation — not in hot-path alloc-banned zone because
    // this struct is tiny and compiler-stack-allocated.
    struct FusedFFNParamsC { uint32_t gate_rows, gate_cols, down_rows, down_cols, group_size, bits; };
    FusedFFNParamsC params { gate_rows, gate_cols, down_rows, down_cols, group_size, bits };

    // ── Wrap raw pointers in MTLBuffers (no-copy) ─────────────
    @autoreleasepool {
        // Compute byte sizes for each sub-tensor (assuming gate/up are same shape and down is transpose)
        uint64_t packed_bytes = static_cast<uint64_t>(gate_rows) * gate_cols * bits / 8;
        uint64_t scale_bytes  = static_cast<uint64_t>(gate_rows) * gate_cols / group_size * sizeof(uint16_t);
        uint64_t input_bytes  = static_cast<uint64_t>(gate_cols)  * sizeof(float);
        uint64_t output_bytes = static_cast<uint64_t>(down_rows)  * sizeof(float);

        NSUInteger off_gp = 0, off_gs = 0, off_up = 0, off_us = 0, off_dp = 0, off_ds = 0;
        id<MTLBuffer> buf_gp = get_registered_buffer(ctx, packed_gate,  packed_bytes, off_gp);
        id<MTLBuffer> buf_gs = get_registered_buffer(ctx, scales_gate,  scale_bytes,  off_gs);
        id<MTLBuffer> buf_up = get_registered_buffer(ctx, packed_up,    packed_bytes, off_up);
        id<MTLBuffer> buf_us = get_registered_buffer(ctx, scales_up,    scale_bytes,  off_us);
        id<MTLBuffer> buf_dp = get_registered_buffer(ctx, packed_down,  packed_bytes, off_dp);
        id<MTLBuffer> buf_ds = get_registered_buffer(ctx, scales_down,  scale_bytes,  off_ds);

        id<MTLBuffer> buf_in = ctx->input_buf;
        id<MTLBuffer> buf_hd = ctx->hidden_buf;
        id<MTLBuffer> buf_ou = ctx->output_buf;
        
        NSUInteger hd_offset = expert_index * ctx->max_rows * sizeof(float);
        NSUInteger ou_offset = expert_index * ctx->max_rows * sizeof(float);

        std::memcpy([buf_in contents], input_vec, input_bytes);

        // ── Encode and commit ─────────────────────────────────────
        id<MTLCommandBuffer>         cmd  = [ctx->queue commandBuffer];
        id<MTLComputeCommandEncoder> enc  = [cmd computeCommandEncoder];

        // ── Pass 1: smoe_gate_up ──────────────────────────────────
        [enc setComputePipelineState:ctx->gate_up_pso];
        [enc setBuffer:buf_gp offset:off_gp atIndex:0];
        [enc setBuffer:buf_gs offset:off_gs atIndex:1];
        [enc setBuffer:buf_up offset:off_up atIndex:2];
        [enc setBuffer:buf_us offset:off_us atIndex:3];
        [enc setBuffer:buf_in offset:0      atIndex:6];
        [enc setBuffer:buf_hd offset:hd_offset atIndex:7];
        // setBytes: the params struct is 24 bytes — inlined into the
        // command stream. The old newBufferWithBytes here was a heap
        // allocation per dispatch, in the hot loop.
        [enc setBytes:&params length:sizeof(params) atIndex:9];
    // Threadgroup SRAM: the WHOLE input vector, staged once per
    // threadgroup (simdgroup-per-row contract; 16 KB at d_model 4096,
    // under the 32 KB limit up to cols 8192).
    [enc setThreadgroupMemoryLength:gate_cols * sizeof(float) atIndex:0];

    {
        // One SIMDGROUP per output row: 256 threads = 8 rows per
        // threadgroup → ceil(rows/8) threadgroups (192 at ffn_dim 1536;
        // the old thread-per-row grid was 6 — occupancy-starved AND
        // uncoalesced: 22.6 vs 158 GB/s, scratch/kernel_bench_results.md).
        NSUInteger tgroup = 256;
        MTLSize tgSize    = MTLSizeMake(tgroup, 1, 1);
        MTLSize gridGroups  = MTLSizeMake((gate_rows + 7) / 8, 1, 1);
        [enc dispatchThreadgroups:gridGroups threadsPerThreadgroup:tgSize];
        [enc memoryBarrierWithScope:MTLBarrierScopeBuffers];
    }

    // Explicit barrier to ensure gate_up finishes writing to buf_hd before down reads it
    if (@available(macOS 10.14, *)) {
        [enc memoryBarrierWithScope:MTLBarrierScopeBuffers];
    } else {
        [enc endEncoding];
        enc = [cmd computeCommandEncoder];
    }

    // ── Pass 2: smoe_down ─────────────────────────────────────
    [enc setComputePipelineState:ctx->down_pso];
    [enc setBuffer:buf_dp offset:off_dp atIndex:4];
    [enc setBuffer:buf_ds offset:off_ds atIndex:5];
    [enc setBuffer:buf_hd offset:hd_offset atIndex:7];
    [enc setBuffer:buf_ou offset:ou_offset atIndex:8];
    [enc setBytes:&params length:sizeof(params) atIndex:9];
    [enc setThreadgroupMemoryLength:down_cols * sizeof(float) atIndex:0];

    {
        NSUInteger tgroup = 256;
        MTLSize tgSize   = MTLSizeMake(tgroup, 1, 1);
        MTLSize gridGroups = MTLSizeMake((down_rows + 7) / 8, 1, 1);
        [enc dispatchThreadgroups:gridGroups threadsPerThreadgroup:tgSize];
        [enc memoryBarrierWithScope:MTLBarrierScopeBuffers];
    }

    [enc endEncoding];

    // Asynchronous commit - use completion handler to signal when done
    __block uint64_t local_dispatch_count = 0;

    [cmd addCompletedHandler:^(id<MTLCommandBuffer> buffer) {
        // This is called asynchronously when the command buffer completes
        local_dispatch_count = ctx->dispatch_count.fetch_add(1, std::memory_order_relaxed);
    }];

    ctx->signaled_value++;
    uint64_t wait_val = ctx->signaled_value;
    [cmd encodeSignalEvent:ctx->shared_event value:wait_val];

    [cmd commit];

    return (void*)(uintptr_t)wait_val;

    } // end @autoreleasepool
}

void smoe_metal_wait(SmoeMetalCtx* ctx, void* handle, float* output_vec, uint32_t expert_index, uint32_t cols) {
    if (!ctx || !handle) return;
    uint64_t val = (uint64_t)(uintptr_t)handle;
    while (ctx->shared_event.signaledValue < val) {
        std::this_thread::yield();
    }
    std::memcpy(output_vec, ((float*)[ctx->output_buf contents]) + expert_index * ctx->max_rows, cols * sizeof(float));
}

void* smoe_metal_fused_ffn_group(SmoeMetalCtx*        ctx,
                                 const SmoeExpertBlob* experts,
                                 uint32_t              n_experts,
                                 const float*          input_vec,
                                 uint32_t              gate_rows,
                                 uint32_t              gate_cols,
                                 uint32_t              down_rows,
                                 uint32_t              down_cols,
                                 uint32_t              group_size,
                                 uint32_t              bits)
{
    if (!ctx || n_experts == 0) return nullptr;

    struct FusedFFNParamsC { uint32_t gate_rows, gate_cols, down_rows, down_cols, group_size, bits; };
    FusedFFNParamsC params { gate_rows, gate_cols, down_rows, down_cols, group_size, bits };

    @autoreleasepool {
        const uint64_t packed_bytes = static_cast<uint64_t>(gate_rows) * gate_cols * bits / 8;
        const uint64_t scale_bytes  = static_cast<uint64_t>(gate_rows) * gate_cols / group_size * sizeof(uint16_t);
        const uint64_t input_bytes  = static_cast<uint64_t>(gate_cols) * sizeof(float);

        // One input copy for the whole group — every expert of a layer
        // consumes the same normed hidden state.
        std::memcpy([ctx->input_buf contents], input_vec, input_bytes);

        id<MTLCommandBuffer>         cmd = [ctx->queue commandBuffer];
        id<MTLComputeCommandEncoder> enc = [cmd computeCommandEncoder];

        // Simdgroup-per-row contract: 256 threads = 8 rows per
        // threadgroup, grid ceil(rows/8), threadgroup memory holds the
        // whole staged input vector (see kernel header in kMetalSource).
        const NSUInteger tgroup = 256;
        const MTLSize tgSize    = MTLSizeMake(tgroup, 1, 1);
        const MTLSize gridGate  = MTLSizeMake((gate_rows + 7) / 8, 1, 1);
        const MTLSize gridDown  = MTLSizeMake((down_rows + 7) / 8, 1, 1);

        // ── Pass 1: smoe_gate_up for every expert ─────────────────
        // Shape/params/input are identical across the group — bound
        // once. Only the weight buffers and the per-expert hidden
        // region change between dispatches.
        [enc setComputePipelineState:ctx->gate_up_pso];
        [enc setBuffer:ctx->input_buf offset:0 atIndex:6];
        [enc setBytes:&params length:sizeof(params) atIndex:9];
        [enc setThreadgroupMemoryLength:gate_cols * sizeof(float) atIndex:0];

        for (uint32_t i = 0; i < n_experts; ++i) {
            NSUInteger off_gp = 0, off_gs = 0, off_up = 0, off_us = 0;
            id<MTLBuffer> buf_gp = get_registered_buffer(ctx, experts[i].packed_gate, packed_bytes, off_gp);
            id<MTLBuffer> buf_gs = get_registered_buffer(ctx, experts[i].scales_gate, scale_bytes,  off_gs);
            id<MTLBuffer> buf_up = get_registered_buffer(ctx, experts[i].packed_up,   packed_bytes, off_up);
            id<MTLBuffer> buf_us = get_registered_buffer(ctx, experts[i].scales_up,   scale_bytes,  off_us);

            [enc setBuffer:buf_gp offset:off_gp atIndex:0];
            [enc setBuffer:buf_gs offset:off_gs atIndex:1];
            [enc setBuffer:buf_up offset:off_up atIndex:2];
            [enc setBuffer:buf_us offset:off_us atIndex:3];
            [enc setBuffer:ctx->hidden_buf
                   offset:experts[i].slot * ctx->max_rows * sizeof(float)
                  atIndex:7];
            [enc dispatchThreadgroups:gridGate threadsPerThreadgroup:tgSize];
        }

        // One barrier for the whole group: every down pass reads only
        // its own expert's hidden region, written by pass 1 above.
        [enc memoryBarrierWithScope:MTLBarrierScopeBuffers];

        // ── Pass 2: smoe_down for every expert ────────────────────
        [enc setComputePipelineState:ctx->down_pso];
        [enc setBytes:&params length:sizeof(params) atIndex:9];
        [enc setThreadgroupMemoryLength:down_cols * sizeof(float) atIndex:0];

        for (uint32_t i = 0; i < n_experts; ++i) {
            NSUInteger off_dp = 0, off_ds = 0;
            id<MTLBuffer> buf_dp = get_registered_buffer(ctx, experts[i].packed_down, packed_bytes, off_dp);
            id<MTLBuffer> buf_ds = get_registered_buffer(ctx, experts[i].scales_down, scale_bytes,  off_ds);

            const NSUInteger region = experts[i].slot * ctx->max_rows * sizeof(float);
            [enc setBuffer:buf_dp offset:off_dp atIndex:4];
            [enc setBuffer:buf_ds offset:off_ds atIndex:5];
            [enc setBuffer:ctx->hidden_buf offset:region atIndex:7];
            [enc setBuffer:ctx->output_buf offset:region atIndex:8];
            [enc dispatchThreadgroups:gridDown threadsPerThreadgroup:tgSize];
        }

        [enc endEncoding];

        [cmd addCompletedHandler:^(id<MTLCommandBuffer> buffer) {
            (void)buffer;
            ctx->dispatch_count.fetch_add(n_experts, std::memory_order_relaxed);
        }];

        ctx->signaled_value++;
        uint64_t wait_val = ctx->signaled_value;
        [cmd encodeSignalEvent:ctx->shared_event value:wait_val];

        [cmd commit];

        return (void*)(uintptr_t)wait_val;
    } // end @autoreleasepool
}

void* smoe_metal_fused_ffn_batch(SmoeMetalCtx*   ctx,
                                 const uint8_t*  packed_gate,
                                 const uint16_t* scales_gate,
                                 const uint8_t*  packed_up,
                                 const uint16_t* scales_up,
                                 const uint8_t*  packed_down,
                                 const uint16_t* scales_down,
                                 const float*    input_mat,
                                 uint32_t        batch,
                                 uint32_t        gate_rows,
                                 uint32_t        gate_cols,
                                 uint32_t        down_rows,
                                 uint32_t        down_cols,
                                 uint32_t        group_size,
                                 uint32_t        bits)
{
    if (!ctx || !ctx->gate_up_batch_pso || batch == 0 ||
        batch > SMOE_MAX_FFN_BATCH ||
        gate_rows > SMOE_MAX_FFN_BATCH_DIM || gate_cols > SMOE_MAX_FFN_BATCH_DIM ||
        down_rows > SMOE_MAX_FFN_BATCH_DIM || down_cols > SMOE_MAX_FFN_BATCH_DIM) {
        return nullptr; // caller falls back to the per-token path
    }

    struct FusedFFNBatchParamsC {
        uint32_t gate_rows, gate_cols, down_rows, down_cols, group_size, bits, batch;
    };
    FusedFFNBatchParamsC params { gate_rows, gate_cols, down_rows, down_cols,
                                  group_size, bits, batch };

    @autoreleasepool {
        uint64_t packed_bytes = static_cast<uint64_t>(gate_rows) * gate_cols * bits / 8;
        uint64_t scale_bytes  = static_cast<uint64_t>(gate_rows) * gate_cols / group_size * sizeof(uint16_t);

        NSUInteger off_gp = 0, off_gs = 0, off_up = 0, off_us = 0, off_dp = 0, off_ds = 0;
        id<MTLBuffer> buf_gp = get_registered_buffer(ctx, packed_gate,  packed_bytes, off_gp);
        id<MTLBuffer> buf_gs = get_registered_buffer(ctx, scales_gate,  scale_bytes,  off_gs);
        id<MTLBuffer> buf_up = get_registered_buffer(ctx, packed_up,    packed_bytes, off_up);
        id<MTLBuffer> buf_us = get_registered_buffer(ctx, scales_up,    scale_bytes,  off_us);
        id<MTLBuffer> buf_dp = get_registered_buffer(ctx, packed_down,  packed_bytes, off_dp);
        id<MTLBuffer> buf_ds = get_registered_buffer(ctx, scales_down,  scale_bytes,  off_ds);

        std::memcpy([ctx->batch_in_buf contents], input_mat,
                    static_cast<size_t>(batch) * gate_cols * sizeof(float));

        id<MTLCommandBuffer>         cmd = [ctx->queue commandBuffer];
        id<MTLComputeCommandEncoder> enc = [cmd computeCommandEncoder];

        // Pass 1: gate+up+SiLU for all batch rows of this expert
        [enc setComputePipelineState:ctx->gate_up_batch_pso];
        [enc setBuffer:buf_gp offset:off_gp atIndex:0];
        [enc setBuffer:buf_gs offset:off_gs atIndex:1];
        [enc setBuffer:buf_up offset:off_up atIndex:2];
        [enc setBuffer:buf_us offset:off_us atIndex:3];
        [enc setBuffer:ctx->batch_in_buf     offset:0 atIndex:6];
        [enc setBuffer:ctx->batch_hidden_buf offset:0 atIndex:7];
        [enc setBytes:&params length:sizeof(params) atIndex:9];
        [enc setThreadgroupMemoryLength:256 * 2 * sizeof(float) atIndex:0];
        {
            MTLSize tg   = MTLSizeMake(256, 1, 1);
            MTLSize grid = MTLSizeMake((gate_rows + 255) / 256, batch, 1);
            [enc dispatchThreadgroups:grid threadsPerThreadgroup:tg];
        }
        [enc memoryBarrierWithScope:MTLBarrierScopeBuffers];

        // Pass 2: down projection for all batch rows
        [enc setComputePipelineState:ctx->down_batch_pso];
        [enc setBuffer:buf_dp offset:off_dp atIndex:4];
        [enc setBuffer:buf_ds offset:off_ds atIndex:5];
        [enc setBuffer:ctx->batch_hidden_buf offset:0 atIndex:7];
        [enc setBuffer:ctx->batch_out_buf    offset:0 atIndex:8];
        [enc setBytes:&params length:sizeof(params) atIndex:9];
        [enc setThreadgroupMemoryLength:256 * 2 * sizeof(float) atIndex:0];
        {
            MTLSize tg   = MTLSizeMake(256, 1, 1);
            MTLSize grid = MTLSizeMake((down_rows + 255) / 256, batch, 1);
            [enc dispatchThreadgroups:grid threadsPerThreadgroup:tg];
        }
        [enc endEncoding];

        [cmd addCompletedHandler:^(id<MTLCommandBuffer> buffer) {
            ctx->dispatch_count.fetch_add(1, std::memory_order_relaxed);
        }];

        ctx->signaled_value++;
        uint64_t wait_val = ctx->signaled_value;
        [cmd encodeSignalEvent:ctx->shared_event value:wait_val];
        [cmd commit];

        return (void*)(uintptr_t)wait_val;
    }
}

void smoe_metal_wait_ffn_batch(SmoeMetalCtx* ctx, void* handle,
                               float* out_mat, uint32_t batch, uint32_t cols) {
    if (!ctx || !handle) return;
    uint64_t val = (uint64_t)(uintptr_t)handle;
    while (ctx->shared_event.signaledValue < val) {
        std::this_thread::yield();
    }
    std::memcpy(out_mat, [ctx->batch_out_buf contents],
                static_cast<size_t>(batch) * cols * sizeof(float));
}

uint64_t smoe_metal_kernel_dispatches(const SmoeMetalCtx* ctx) {
    if (!ctx) return 0;
    return ctx->dispatch_count.load(std::memory_order_relaxed);
}

void smoe_metal_register_buffer(SmoeMetalCtx* ctx, const void* ptr, size_t size_in_bytes) {
    if (!ctx || !ptr || size_in_bytes == 0) return;

    uintptr_t p = reinterpret_cast<uintptr_t>(ptr);
    for (const auto& reg : ctx->registered_buffers) {
        uintptr_t base = reinterpret_cast<uintptr_t>(reg.ptr);
        if (p >= base && (p + size_in_bytes) <= (base + reg.length)) return;
    }

    size_t aligned = (size_in_bytes + (smoe::PAGE_SIZE - 1)) & ~(smoe::PAGE_SIZE - 1);
    id<MTLBuffer> buf = [ctx->device newBufferWithBytesNoCopy:const_cast<void*>(ptr)
                                                       length:aligned
                                                      options:MTLResourceStorageModeShared
                                                  deallocator:nil];
    if (buf) {
        ctx->registered_buffers.push_back({ptr, aligned, buf});
    } else {
        std::fprintf(stderr, "[smoe_metal] ERROR: failed to register buffer at %p (%zu bytes)\n", ptr, size_in_bytes);
    }
}



// Encode one bf16 matvec dispatch, picking the coalesced simdgroup-
// per-row kernel whenever its contract holds — weight pointer 16-byte
// aligned, cols % 8 == 0 (keeps every row base 16-byte aligned for the
// uint4 loads), staged input within the device threadgroup memory
// limit. The thread-per-row twin covers everything else (e.g. the
// >8192-col dense/shared FFN matrices of DeepSeek-family models).
// Returns false only if buffer wrapping failed.
static bool encode_scout_matvec_bf16(SmoeMetalCtx* ctx,
                                     id<MTLComputeCommandEncoder> enc,
                                     const uint16_t* weight,
                                     const float*    input,
                                     float*          output,
                                     uint32_t rows, uint32_t cols)
{
    size_t weight_bytes = static_cast<size_t>(rows) * cols * sizeof(uint16_t);
    size_t input_bytes  = static_cast<size_t>(cols) * sizeof(float);
    size_t output_bytes = static_cast<size_t>(rows) * sizeof(float);

    NSUInteger off_wt=0, off_in=0, off_ou=0;
    id<MTLBuffer> buf_wt = get_registered_buffer(ctx, weight, weight_bytes, off_wt);
    id<MTLBuffer> buf_in = get_registered_buffer(ctx, input,  input_bytes,  off_in);
    id<MTLBuffer> buf_ou = get_registered_buffer(ctx, output, output_bytes, off_ou);
    if (!buf_wt || !buf_in || !buf_ou) return false;

    const bool sg_ok = ctx->scout_matvec_bf16_sg_pso != nil
        && (reinterpret_cast<uintptr_t>(weight) & 15u) == 0
        && (cols & 7u) == 0
        && static_cast<size_t>(cols) * sizeof(float) <= ctx->max_tg_mem;

    Dims dims { rows, cols };
    [enc setComputePipelineState:(sg_ok ? ctx->scout_matvec_bf16_sg_pso
                                        : ctx->scout_matvec_bf16_pso)];
    [enc setBuffer:buf_wt offset:off_wt atIndex:0];
    [enc setBuffer:buf_in offset:off_in atIndex:1];
    [enc setBuffer:buf_ou offset:off_ou atIndex:2];
    [enc setBytes:&dims length:sizeof(dims) atIndex:3];

    NSUInteger tgroup = 256;
    if (sg_ok) {
        // One SIMDGROUP per output row: 256 threads = 8 rows per
        // threadgroup; the whole input vector staged in tgmem.
        [enc setThreadgroupMemoryLength:static_cast<size_t>(cols) * sizeof(float) atIndex:0];
        [enc dispatchThreadgroups:MTLSizeMake((rows + 7) / 8, 1, 1)
            threadsPerThreadgroup:MTLSizeMake(tgroup, 1, 1)];
    } else {
        // ceil(rows/256) threadgroups, one thread per row.
        [enc setThreadgroupMemoryLength:tgroup * sizeof(float) atIndex:0];
        [enc dispatchThreadgroups:MTLSizeMake((rows + tgroup - 1) / tgroup, 1, 1)
            threadsPerThreadgroup:MTLSizeMake(tgroup, 1, 1)];
    }
    return true;
}

void smoe_metal_scout_matvec_batch_bf16(SmoeMetalCtx* ctx,
                                   const uint16_t** weights,
                                   const float**  inputs,
                                   float**        outputs,
                                   const uint32_t* rows,
                                   const uint32_t* cols,
                                   uint32_t       count)
{
    if (!ctx || count == 0) return;

    @autoreleasepool {
    id<MTLCommandBuffer> cmd = [ctx->queue commandBuffer];
    id<MTLComputeCommandEncoder> enc = [cmd computeCommandEncoder];

    for (uint32_t i = 0; i < count; ++i) {
        if (!encode_scout_matvec_bf16(ctx, enc, weights[i], inputs[i], outputs[i],
                                      rows[i], cols[i])) {
            std::fprintf(stderr, "[smoe_metal] ERROR: failed to wrap batch bf16 pointers.\n");
            return;
        }
        [enc memoryBarrierWithScope:MTLBarrierScopeBuffers];
    }

    [enc endEncoding];
    
    ctx->signaled_value++;
    uint64_t wait_val = ctx->signaled_value;
    [cmd encodeSignalEvent:ctx->shared_event value:wait_val];

    [cmd commit];

    while (ctx->shared_event.signaledValue < wait_val) {
        std::this_thread::yield();
    }
    }
}

void smoe_metal_scout_matvec_group_bf16(SmoeMetalCtx* ctx,
                                   const uint16_t** weights,
                                   const float**  inputs,
                                   float**        outputs,
                                   const uint32_t* rows,
                                   const uint32_t* cols,
                                   uint32_t       count)
{
    if (!ctx || count == 0) return;

    @autoreleasepool {
    id<MTLCommandBuffer> cmd = [ctx->queue commandBuffer];
    id<MTLComputeCommandEncoder> enc = [cmd computeCommandEncoder];

    // No inter-dispatch barriers: outputs are pairwise distinct and no
    // dispatch reads another's output (caller contract), so the GPU may
    // execute all of them concurrently.
    for (uint32_t i = 0; i < count; ++i) {
        if (!encode_scout_matvec_bf16(ctx, enc, weights[i], inputs[i], outputs[i],
                                      rows[i], cols[i])) {
            std::fprintf(stderr, "[smoe_metal] ERROR: failed to wrap group bf16 pointers.\n");
            return;
        }
    }

    [enc endEncoding];

    ctx->signaled_value++;
    uint64_t wait_val = ctx->signaled_value;
    [cmd encodeSignalEvent:ctx->shared_event value:wait_val];

    [cmd commit];

    while (ctx->shared_event.signaledValue < wait_val) {
        std::this_thread::yield();
    }
    }
}

void smoe_metal_scout_matvec_bf16(SmoeMetalCtx* ctx,
                             const uint16_t* weight,
                             const float*  input_vec,
                             float*        output_vec,
                             uint32_t      rows,
                             uint32_t      cols)
{
    const uint16_t* weights[1] = { weight };
    const float* inputs[1] = { input_vec };
    float* outputs[1] = { output_vec };
    uint32_t r[1] = { rows };
    uint32_t c[1] = { cols };
    smoe_metal_scout_matvec_batch_bf16(ctx, weights, inputs, outputs, r, c, 1);
}

// Host-side mirrors of the MSL param structs (4-byte fields only —
// identical layout on both sides, safe for setBytes).
struct AttnPrepParamsHost {
    uint32_t head_dim, num_heads, num_kv_heads, rope_half;
    uint32_t slot, kv_dim, has_qk_norm;
};
struct AttnDecodeParamsHost {
    uint32_t head_dim, num_heads, heads_per_kv, kv_dim;
    uint32_t slot, valid, attn_ctx;
    float    scale;
};

void smoe_metal_attention_layer(SmoeMetalCtx* ctx, const SmoeAttnLayerArgs* a)
{
    if (!ctx || !a) return;

    @autoreleasepool {
    id<MTLCommandBuffer> cmd = [ctx->queue commandBuffer];
    id<MTLComputeCommandEncoder> enc = [cmd computeCommandEncoder];

    const size_t cache_bytes = size_t(a->attn_ctx) * a->kv_dim * sizeof(float);

    // ── Pass 1: Q/K/V projections (independent — one barrier after) ──
    {
        const uint16_t* w[3]   = { a->w_q,  a->w_k,  a->w_v  };
        float*          o[3]   = { a->qbuf, a->kbuf, a->vbuf };
        const uint32_t  rows[3]= { a->q_dim, a->kv_dim, a->kv_dim };

        for (int i = 0; i < 3; ++i) {
            if (!encode_scout_matvec_bf16(ctx, enc, w[i], a->normed_in, o[i],
                                          rows[i], a->d_model)) {
                std::fprintf(stderr, "[smoe_metal] ERROR: attention QKV wrap failed.\n");
                [enc endEncoding];
                return;
            }
        }
    }
    [enc memoryBarrierWithScope:MTLBarrierScopeBuffers];

    // ── Pass 2: per-head QK norm + RoPE + KV ring append ──
    {
        NSUInteger off_q = 0, off_k = 0, off_v = 0, off_qn = 0, off_kn = 0,
                   off_c = 0, off_s = 0, off_kc = 0, off_vc = 0;
        size_t head_bytes = size_t(a->head_dim) * sizeof(uint16_t);
        size_t rope_bytes = size_t(a->head_dim / 2) * sizeof(float);
        id<MTLBuffer> buf_q  = get_registered_buffer(ctx, a->qbuf, size_t(a->q_dim) * sizeof(float), off_q);
        id<MTLBuffer> buf_k  = get_registered_buffer(ctx, a->kbuf, size_t(a->kv_dim) * sizeof(float), off_k);
        id<MTLBuffer> buf_v  = get_registered_buffer(ctx, a->vbuf, size_t(a->kv_dim) * sizeof(float), off_v);
        // QK-norm weights may be absent: bind qbuf as a placeholder so
        // the slots are valid; the kernel never reads them then.
        id<MTLBuffer> buf_qn = a->q_norm_w ? get_registered_buffer(ctx, a->q_norm_w, head_bytes, off_qn) : buf_q;
        id<MTLBuffer> buf_kn = a->k_norm_w ? get_registered_buffer(ctx, a->k_norm_w, head_bytes, off_kn) : buf_q;
        id<MTLBuffer> buf_c  = get_registered_buffer(ctx, a->rope_cos, rope_bytes, off_c);
        id<MTLBuffer> buf_s  = get_registered_buffer(ctx, a->rope_sin, rope_bytes, off_s);
        id<MTLBuffer> buf_kc = get_registered_buffer(ctx, a->k_cache, cache_bytes, off_kc);
        id<MTLBuffer> buf_vc = get_registered_buffer(ctx, a->v_cache, cache_bytes, off_vc);
        if (!buf_q || !buf_k || !buf_v || !buf_qn || !buf_kn || !buf_c || !buf_s || !buf_kc || !buf_vc) {
            std::fprintf(stderr, "[smoe_metal] ERROR: attention prep wrap failed.\n");
            [enc endEncoding];
            return;
        }
        AttnPrepParamsHost pp {
            a->head_dim, a->num_heads, a->num_kv_heads, a->head_dim / 2,
            a->slot, a->kv_dim,
            (a->q_norm_w && a->k_norm_w) ? 1u : 0u
        };
        [enc setComputePipelineState:ctx->attn_prep_pso];
        [enc setBuffer:buf_q  offset:off_q  atIndex:0];
        [enc setBuffer:buf_k  offset:off_k  atIndex:1];
        [enc setBuffer:buf_v  offset:off_v  atIndex:2];
        [enc setBuffer:buf_qn offset:(a->q_norm_w ? off_qn : off_q) atIndex:3];
        [enc setBuffer:buf_kn offset:(a->k_norm_w ? off_kn : off_q) atIndex:4];
        [enc setBuffer:buf_c  offset:off_c  atIndex:5];
        [enc setBuffer:buf_s  offset:off_s  atIndex:6];
        [enc setBuffer:buf_kc offset:off_kc atIndex:7];
        [enc setBuffer:buf_vc offset:off_vc atIndex:8];
        [enc setBytes:&pp length:sizeof(pp) atIndex:9];
        [enc setThreadgroupMemoryLength:(a->head_dim + 32) * sizeof(float) atIndex:0];
        [enc dispatchThreadgroups:MTLSizeMake(a->num_heads + a->num_kv_heads, 1, 1)
            threadsPerThreadgroup:MTLSizeMake(a->head_dim, 1, 1)];
    }
    [enc memoryBarrierWithScope:MTLBarrierScopeBuffers];

    // ── Pass 3: GQA attention over the KV ring ──
    {
        NSUInteger off_q = 0, off_kc = 0, off_vc = 0, off_o = 0;
        id<MTLBuffer> buf_q  = get_registered_buffer(ctx, a->qbuf, size_t(a->q_dim) * sizeof(float), off_q);
        id<MTLBuffer> buf_kc = get_registered_buffer(ctx, a->k_cache, cache_bytes, off_kc);
        id<MTLBuffer> buf_vc = get_registered_buffer(ctx, a->v_cache, cache_bytes, off_vc);
        id<MTLBuffer> buf_o  = get_registered_buffer(ctx, a->attn_out, size_t(a->q_dim) * sizeof(float), off_o);
        if (!buf_q || !buf_kc || !buf_vc || !buf_o) {
            std::fprintf(stderr, "[smoe_metal] ERROR: attention decode wrap failed.\n");
            [enc endEncoding];
            return;
        }
        AttnDecodeParamsHost dp {
            a->head_dim, a->num_heads, a->num_heads / a->num_kv_heads, a->kv_dim,
            a->slot, a->valid, a->attn_ctx,
            a->attn_scale
        };
        [enc setComputePipelineState:ctx->attn_decode_pso];
        [enc setBuffer:buf_q  offset:off_q  atIndex:0];
        [enc setBuffer:buf_kc offset:off_kc atIndex:1];
        [enc setBuffer:buf_vc offset:off_vc atIndex:2];
        [enc setBuffer:buf_o  offset:off_o  atIndex:3];
        [enc setBytes:&dp length:sizeof(dp) atIndex:4];
        // Threadgroup plan: staged Q head + score row + simd scratch.
        [enc setThreadgroupMemoryLength:(a->head_dim + a->valid + 32) * sizeof(float) atIndex:0];
        [enc dispatchThreadgroups:MTLSizeMake(a->num_heads, 1, 1)
            threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
    }
    [enc memoryBarrierWithScope:MTLBarrierScopeBuffers];

    // ── Pass 4: O projection ──
    if (!encode_scout_matvec_bf16(ctx, enc, a->w_o, a->attn_out, a->o_out,
                                  a->d_model, a->q_dim)) {
        std::fprintf(stderr, "[smoe_metal] ERROR: attention o_proj wrap failed.\n");
        [enc endEncoding];
        return;
    }

    [enc endEncoding];

    ctx->signaled_value++;
    uint64_t wait_val = ctx->signaled_value;
    [cmd encodeSignalEvent:ctx->shared_event value:wait_val];
    [cmd commit];

    while (ctx->shared_event.signaledValue < wait_val) {
        std::this_thread::yield();
    }
    }
}
